import fs from 'fs';
import path from 'path';
import { getJobStore } from './job-store';
import { ApplicationStatus } from '../shared/types';
import { logger } from '../shared/logger';

const TRACKER_PATH = path.join(__dirname, '../../applications/tracker.md');

const STATUS_SORT_ORDER: Record<ApplicationStatus, number> = {
  applying: 0,
  applied: 1,
  phone_screen: 2,
  interview: 3,
  take_home: 4,
  offer: 5,
  identified: 6,
  needs_manual_apply: 7,
  accepted: 8,
  declined: 9,
  rejected: 10,
  withdrawn: 11,
  no_response: 12,
};

const STATUS_DISPLAY: Record<ApplicationStatus, string> = {
  identified: 'IDENTIFIED',
  applying: 'APPLYING',
  applied: 'APPLIED',
  phone_screen: 'PHONE_SCREEN',
  interview: 'INTERVIEW',
  take_home: 'TAKE_HOME',
  offer: 'OFFER',
  accepted: 'ACCEPTED',
  declined: 'DECLINED',
  rejected: 'REJECTED',
  withdrawn: 'WITHDRAWN',
  no_response: 'NO_RESPONSE',
  needs_manual_apply: 'NEEDS_MANUAL',
};

export function syncTrackerFile(): void {
  const store = getJobStore();
  const apps = store.getAllApplications();
  const listings = store.getAllListings();

  const listingMap = new Map(listings.map((l) => [l.id, l]));

  // Sort: active statuses first, then identified, then terminal
  const sorted = [...apps].sort((a, b) => {
    const orderA = STATUS_SORT_ORDER[a.status] ?? 99;
    const orderB = STATUS_SORT_ORDER[b.status] ?? 99;
    return orderA - orderB;
  });

  const rows = sorted.map((app) => {
    const listing = listingMap.get(app.listingId);
    if (!listing) return null;

    const status = STATUS_DISPLAY[app.status] || app.status.toUpperCase();
    const salary = listing.salaryRange || '—';
    const appliedDate = app.appliedAt ? app.appliedAt.split('T')[0] : '—';
    const followUp = app.followUpDate || '—';
    const method = app.applyMethod ? ` (${app.applyMethod})` : '';
    const notes = [app.notes, method].filter(Boolean).join(' ').trim() || '—';

    return `| ${listing.company} | ${listing.title} | [Link](${listing.url}) | ${salary} | ${status} | ${appliedDate} | ${followUp} | ${notes} |`;
  }).filter(Boolean);

  const today = new Date().toISOString().split('T')[0];
  const md = `# Job Application Tracker

Last updated: ${today}

| Company | Role | URL | Salary Range | Status | Applied Date | Follow-up Date | Notes |
|---------|------|-----|-------------|--------|-------------|----------------|-------|
${rows.join('\n')}

---

*Auto-generated by job search pipeline. Source of truth: SQLite database (data/jobs.db).*
`;

  const dir = path.dirname(TRACKER_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(TRACKER_PATH, md);

  logger.info(`Tracker synced: ${rows.length} entries written to ${TRACKER_PATH}`);
}

export function getTrackerSummary(): string {
  const store = getJobStore();
  const stats = store.getStats();
  const apps = store.getAllApplications();

  const byCounts: Record<string, number> = {};
  for (const app of apps) {
    const display = STATUS_DISPLAY[app.status] || app.status;
    byCounts[display] = (byCounts[display] || 0) + 1;
  }

  const statusLine = Object.entries(byCounts)
    .map(([status, count]) => `${count} ${status}`)
    .join(', ');

  return `Pipeline: ${stats.totalListings} listings, ${stats.totalApplications} tracked | ${statusLine} | Avg score: ${stats.avgScore}`;
}
